#!/usr/bin/env bash

# Tmux
rsync ./tmux/tmux.conf ~/.tmux.conf

# Julia
JULIA_DEPOT_PATH=~/projects/def-sacchi/saraivaq/.julia
mkdir -p $JULIA_DEPOT_PATH/config
mkdir -p $JULIA_DEPOT_PATH/environments
rsync ./julia/startup.jl $JULIA_DEPOT_PATH/config/
rsync -r ./julia/environments/v1.9 $JULIA_DEPOT_PATH/environments/

# Vifm
wget https://github.com/vifm/vifm/releases/download/v0.13/vifm-v0.13-x86_64.AppImage
mkdir -p ~/.bin
mv vifm-v0.13-x86_64.AppImage ~/.bin/vifm
chmod +x ~/.bin/vifm
mkdir -p ~/.config/vifm
rsync ./vifm/vifmrc ~/.config/vifm/

# Neovim
wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
tar xzvf nvim-linux64.tar.gz
rm nvim-linux64.tar.gz
mv nvim-linux64 ~/.bin/
mkdir -p ~/.bin
cd ~/.bin
rm nvim
ln -s nvim-linux64/bin/nvim .
cd -
rsync -r ./nvim ~/.config/
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
pip3 install --upgrade pynvim

# Scripts
mkdir -p ~/.bin
cp -r scripts/* ~/.bin/

# Environment variables
cp ./serverVars ~/.serverVars
if grep -Fxq "source ~/.serverVars" ~/.bashrc
then
    echo "Not putting anything to the .bashrc file since it already has a source call"
else
    cp ~/.bashrc ~/.bashrc.old
    echo "source ~/.serverVars" >> ~/.bashrc
fi
