#!/usr/bin/env zsh

backupDirList=$HOME/Files/Mega/backupdirs
#for dir in $(cat $backupDirList); do
    #echo $dir
    ##cd $dir
    ##duplicacy backup
#done
cd $HOME
while IFS='' read -r LINE || [ -n "${LINE}" ]; do
    echo "processing line: ${LINE}"
    kopia snapshot "$LINE"
done < $backupDirList
