#!/usr/bin/env sh
if [ $# -ge 1 ]; then
        game="$(which $1)"
        #openbox="$(which openbox-session)"
        tmpgame="/tmp/tmpgame.sh"
        DISPLAY=:1.0
        #echo -e "${openbox} &\n${game}" > ${tmpgame}
        echo "starting ${game}"
        #xinit ${tmpgame} -- :1 -xf86config xorg-single.conf -configdir empty vt8 || exit 1
        #xinit ${tmpgame} -- :1 -configdir empty vt8 || exit 1
        xinit ${tmpgame} -- :1 vt$XDG_VTNR || exit 1
else
        echo "not a valid argument"
fi
