#!/usr/bin/env zsh
kitty -e watch -n 0.5 cat /sys/class/drm/card0/device/pp_dpm_sclk &
kitty -e watch -n 0.5 cat /sys/class/drm/card0/device/pp_dpm_mclk &
kitty -e sudo watch -n 0.5 cat /sys/kernel/debug/dri/0/amdgpu_pm_info &
exit
