#!/usr/bin/zsh

date=$(date)

cp "/mnt/w10/Users/atila/AppData/Roaming/DarkSoulsIII/0110000105d10959/DS30000.sl2" "/home/atila/.steam/steam/steamapps/compatdata/374320/pfx/drive_c/users/steamuser/Application Data/DarkSoulsIII/0110000105d10959/DS30000.sl2"

cd "/home/atila/.steam/steam/steamapps/compatdata/374320/pfx/drive_c/users/steamuser/Application Data/DarkSoulsIII/0110000105d10959"

git add *
git commit -m "Pulling save from w10: $date"

