#!/usr/bin/env zsh

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 7 -yoffset -75 -xoffset 69 -line-padding 4 -columns 2 -width 25 -lines 30 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme "Papirus" -font "Fantasque Sans Mono 10"
